//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public int Enrollment_Id { get; set; }
        public Nullable<int> Course_id { get; set; }
        public string Student_id { get; set; }
        public Nullable<bool> Is_Paid { get; set; }
        public Nullable<int> semester_id { get; set; }
        public Nullable<int> Course_mark { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Courses_Offered Courses_Offered { get; set; }
        public virtual semester semester { get; set; }
    }
}
