//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project8.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RegistrationPeriod
    {
        public int id { get; set; }
        public Nullable<int> semester_id { get; set; }
        [Required]
        [Display(Name = "Start Date")]
        public Nullable<System.DateTime> start_date { get; set; }
        [Required]
        [Display(Name = "End Date")]
        public Nullable<System.DateTime> end_date { get; set; }

        public virtual semester semester { get; set; }
    }
}
