//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Transaction_Id { get; set; }
        public Nullable<System.DateTime> Transaction_Date { get; set; }
        public string FullName { get; set; }
        public string CardNumber { get; set; }
        public Nullable<int> CVC { get; set; }
        public Nullable<System.DateTime> Visa_ExpireDate { get; set; }
        public Nullable<bool> User_Action { get; set; }
        public Nullable<int> Amount { get; set; }
        public string UserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
