//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cours()
        {
            this.Courses1 = new HashSet<Cours>();
            this.Courses_Offered = new HashSet<Courses_Offered>();
        }
    
        public int Course_Id { get; set; }
        public string Course_Name { get; set; }
        public Nullable<int> Number_Of_Hours { get; set; }
        public string Course_Description { get; set; }
        public Nullable<int> Major_Id { get; set; }
        public string syllabus { get; set; }
        public Nullable<int> dependent_Course { get; set; }
    
        public virtual Major Major { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cours> Courses1 { get; set; }
        public virtual Cours Cours1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Courses_Offered> Courses_Offered { get; set; }
    }
}
